apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service_name }}
  labels: 
    app: {{ .Values.service_name }}

spec:
  replicas: {{ .Values.replica_count }}
  selector:
    matchLabels: 
      app: {{ .Values.service_name }}

  template:
    metadata:
      labels: 
        app: {{ .Values.service_name }}

    spec:
      containers:
      - name: {{ .Values.service_name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- if  .Values.loadBalancer }}
        ports:
        - containerPort: {{ .Values.port }}
        {{- end }}
        {{- if not .Values.loadBalancer }}
        envFrom:
          - configMapRef:
              name: {{ .Values.service_name }}
        {{- end }}