{{ if .Values.db_enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.service_name }}-db

spec:
  template:
    spec:
      restartPolicy: {{ .Values.restart_policy }}

      containers:
      - name: {{ .Values.db_image.name }}
        image: {{ .Values.db_image.repository }}:{{ .Values.db_mage.tag }}
        imagePullPolicy: {{ .Values.db_image.imagePullPolicy }}
        
        envFrom:
          - configMapRef:
              name: {{ .Values.service_name }}
{{ end }}
