apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
  {{- if .Values.loadBalancer}}
  annotations:
{{- .Values.anote | nindent 4 }}
   {{- end }}

spec:
  {{- if .Values.loadBalancer }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }} 
  {{- else }}
  type: ClusterIP
  {{- end }}

  selector:
    app: {{ .Values.service_name }}
    
  ports:
{{- toYaml .Values.ports | nindent 2 }}