apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
  annotations:
{{- .Values.anote | nindent 4 }}
spec:
  type: LoadBalancer
  loadBalancerIP: "9.205.152.5" # Put the real IP address here
  selector:
    app: {{ .Values.service_name }}
  ports:
{{- toYaml .Values.ports | nindent 2 }}